-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', UF.BOARD_ID, '/', UF.FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD UB JOIN USED_GOODS_FILE UF ON UB.BOARD_ID = UF.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY UF.FILE_ID DESC